### ISSUE TITLE
Checks should access data using...

### ISSUE THREAD

**Issue by leinfelder** [NCEAS/mdqengine#2]
On today's call we discussed various ways to locate the data that is described in metadata in order to perform congruency checks on it. Here are avenues we'd like to support:

- [ ] Entity's online distribution URL - should work for all dialects
- [ ] Entity's EML@id attribute (append to CN resolve URL) - EML specific
- [ ] Ecogrid URL (parse id from it and use in CN resolve URL) - KNB+EML specific
- [ ] URI from ORE, looked up using entity id found in metadata doc - assumes the dialect has data id included somewhere in the metadata

**Comment by amoeba** [comment]
Since we decided on keeping with our model of 'if you can xpath it, you can check it", this issue seems closeable.

**Comment by mbjones** [comment]
Are you saying that data entities are not available to the check?  That would not meet our needs, as we definitely have use cases that require checks to process both metadata and data.  Personally, I think that checks should be written such that the metadata and data are passed into the check in a well-known way, so that the check can be run from multiple environments.  For example, if a call-back method were used, then the call-back would take data and metadata as parameters.  Then, this call-back could either be called by the check framework when it is embedded, or it could be called locally for testing the check code.  However we decide to do it, the check code in R/python/etc must be given:
- full metadata document
- all data objects

It would also be good to do this in an efficient framework so that suites of checks that run on the same data package can be passed the data without transferring it over the network multiple times -- in other words, we need some sort of `setUp` style system where the data are transferred and then multiple checks are run on that set of data.

**Comment by leinfelder** [comment]
Matt, this ticket is stating that we didn't think it was appropriate for the engine to be responsible for fetching the data bytes and transferring it to <some scripting environment>. We also suggest multiple ways that a check can extract pointers to where data exists so that the check can fetch the bytes as needed. 

This does not address your concern about multiple checks downloading the same data repeatedly, but I thought we were trying to keep the checks independent from the suites that contain them.

I can investigate persisting a scripting environment across multiple check dispatches, though we start getting into some wild-west territory here since a suite can contain heterogeneous check implementations  (JS, R, Python, Java....) and we would not be able to persist state across all those different environments.

**Comment by amoeba** [comment]
#9 was meant to address the multiple downloading issue.

Automatically provisioning the check with the data objects is obviously possible but does not mesh with our other design choice: Leaving the decision of **what** concepts exist **where** in the metadata to the suite.

#9 addresses this in what I think is a fairly clean way. The check suite says "The data are described at these XPATHs and I want each check to have access to the bytes corresponding to that data when they run.

@leinfelder it feels like we certainly need to persist state between check runs. If the check has to re-download the data every time, we would be suggesting check writers do all of their data checks in one mega-check when we really want to encourage more small tests. Or at least I want to encourage that.

**Comment by leinfelder** [comment]
This isn't really an issue and is left up to the check writer to find appropriate data identifiers and/or URLs in the metadata documents they are processing.

**Comment by mbjones** [comment]
In addition to the mechanism's listed in this ticket, I'd like to see the checks be able to access the data  without resolving a URI or other external mechanism.  I imagine some checks that will operate on data that is relatively large, and it would be most efficient for the MQE itself to arrange the transfer, rather than the check making an external call.  This would be especially true for a series of checks in which they each need access to one or more large data files, and so its best not to transfer the data multiple times from an external URL.  A check still __can__ check a URL if it so desires (e.g., looking for 404s), but it shouldn't have to.

This is closely related to issue #9 for how to get data once for a suite.  The proposed solution, that the first check in the series gets the data, is quite fragile and creates dependencies on check ordering.  I'd prefer to see a common library/function approach, so that any check can get access to the data and metadata, checks can be run in any order, and things will still be efficient.  I definitely see a use for recommendations to include some but not all of the checks in another rec, and if they happen to exclude the first one that retrieved the data, then everything breaks with the current model.

Let's please discuss this further. I'd like to see two main features:
- Data are only downloaded/transferred once when a rec is run
- Checks are atomic and independent of one another so they can be run in any rec, and in any order

**Comment by leinfelder** [comment]
A check that depends on the suite ("rec" as you still call it) would also break if it were included in a suite that neglected to load the data.
The way I see it, if we want checks to be able to inherit state from previous checks, we cannot also allow them to be run in any order. Cake and eat it too...

**Comment by leinfelder** [comment]
Can you elaborate on this?
> I'd like to see the checks be able to access the data without resolving a URI or other external mechanism

I take that as either a) magic, or b) that the engine is running on the same machine that houses the data (e.g., MN repository). for option B - just guessing :) - a check is free to use it's intimate knowledge of the MN store to try to find the data on disk. For Metacat, that might be to query the the postgres DB to find the docid from the pid in order to find the file located in /var/metacat/data. That's quite a feat when we've gone through years of work to expose all our content over standard APIs...

Is there an option C I am missing?

**Comment by gothub** [comment]
Looks like we have a new topic of "how to get the data" in addition to "how to reuse the data once we have got it".

In regard to the latter point, a check library could have a mechanism that looks
like a cache, but really is using the inherit state mechanism that has already been implemented.
Each check could access the data it needs by specifying the metadata or data URL:

```{r}
mydf <- getCache(URL, as="data.frame")
```

The `getCache` function checks a known location in the inherited variables to see if the URL
has been downloaded and converted to the specified format. If yes, then the data is retrieved from
the 'cache', otherwise the library downloads it and stores it in the cache, which will be available
for later checks.

The check doesn't have to know how or when the data has been accessed before, the suite doesn't have to know what data the check needs and checks would be independent from each other in terms of accessing data.

**Comment by mbjones** [comment]
Peter -- that's exactly the type of design I was thinking of. Whether that is implemented in the R dispatcher or as a function in a utility library  that can be used by a check is open for discussion.  But that's the idea.

**Comment by leinfelder** [comment]
Again, a check is free to use any "utility library" it wishes. If the cache you describe (which I like) is a package in R, then great. What gets sticky is crossing scripting environments when, say, I want to use the cache in python. Maybe we decide not to support that?

**Comment by gothub** [comment]
I don't think that the inherit state mechanism should change at all. The check library would rely
on the current mechanism to share data between checks, but would provide a controlled way to
access those data. 

I just ran a test suite where the first check (R) downloaded a csv, saved as  a data.frame and then
the next check (python) accessed the data as a list. If there really isn't any data loss with this mechanism then great, let's keep it! With the caching thing, the equivalent would be achieved with:

```
# first check in R
# data is downloaded and stored in the cache (variable in global environment)
myTemData <- getCache(someURL, as="data.frame")
```

```
# second check in python
# data is obtained from the cache (global variable inherited from previous check)
myTempData = getCache(someUR, as="list")
```

The check writer would have to known appropriate types to request.

**Comment by leinfelder** [comment]
So there's a getCache() method implemented in every environment we support?

**Comment by mbjones** [comment]
A utility library for the environments we support would be a good idea.

**Comment by leinfelder** [comment]
We've now implemented the caching system and it can be used across checks and suites and does not require any specific order of checks within a suite.
