### ISSUE TITLE
Consider namespacing the "standard" variables we provide to checks

### ISSUE THREAD

**Issue by leinfelder** [NCEAS/mdqengine#26]
I suspect it will be very possible for check writers to inadvertently use some of our reserved variable names in their own code. I'm not exactly sure how this will work in every scripting env, but having an object that contains the variables seems much safer.

So instead of
`var result = {value: true, message="It worked"}; # access result.value`

We would have:
`var mdq = {result: {value: true, message="It worked"}}; # access mdq.result.value`

**Comment by amoeba** [comment]
I think this is great to tackle in some way. I think I like your suggestion just fine.

I wanted to lay out a broader set of options too, just in case there was any interest or in the hopes other ideas may come out:

- Use an easy to collide name like `result` but either:
  - Let the check writer shoot themselves in the foot (stauts quo) and do nothing to save them
  - Validate the structure of the Result, or even use a Class for it. Let the user walk over it but make the check ERROR out if the object doesn't validate
- Use a hard to collide name and hope the user doesn't muck it up:
  - `mdq = { result: { value: ...} }` (meta object for all mdq state)
  - `mdq_result = { value: ... }` (one object per mdq state object, status/result/message)
  
  Not that aesthetically pleasing but easy to implement and unlikely to collide.

- Make the easy to collide variable name hard to collide, like
  - `.result` `.status` `.message` in R or `_result` `_status`, _`message_ in Python (<- this is probably a terrible idea)

  While probably a terrible idea, I like the aesthetics of the non-namespaced variables names

- Analyze/lint the check code before executing to see if it uses reserved words and present an error

  A little more involved than the other examples

- Use functions instead of variables to set result/status/message. e.g.
  - Set the STATUS: `set_success()`, or `status_success()` which sets either namespaced or not namespaced variables behind the scenes
  - Set the `message`: `set_message(paste(expected, "keywords were expected but", length(keywords), "were found.")`
  - Set a return value: `set_value(some_variable)` which appends to a list. Calling multiple times would add multiple values. Could be called `save_value` or `add_value` or something.
  - Set a rich media return value: `set_value(tmp, type = "image/png")` which appends to the same list as above. Calling multiple times would add multiple values.

Are there any other options?

I think the pros/cons of each of these are pretty straight forward. If someone's coming from the R or Python world, they may expect special functions (`expect_length`) or even language keywords (`asssert`) for the parts of their check code that do the actual checking (versus the parts that are setup).

A con of namespacing, to me, is that it's harder to remember the name you have to set but someone could argue that it's not very hard to learn a special variable name or two and look it up every once in a while.

**Comment by gothub** [comment]
@amoeba what about a blend of your ideas of "easy to collide" and "hard to collide", i.e.
the variable names:

- mdq_result
- mdq_status
- mdq_message

I like the idea of keeping this part of the API really simple and easy to remember. Passing
back a complex value is fine, but the check writer has to remember the structure, which may
be different for each environment, and easy to get wrong, i.e. wrong order of result, status, message in the structure.

Keep the names the same in all environments, use underscores as Java doesn't like '.' in 
variable names.

**Comment by leinfelder** [comment]
@gothub Well, we're heading down the road to complex result type - see issue #24 and #25 - but I'd hate to make it hard for check writers to actually write checks and return a simple value. Right now we support both: you can just return a value and set a couple simple string variables (message, status) or you can construct a true Result object and return that. See the PythonDispatcherTest.testResult() method for an example of what I am talking about.

**Comment by leinfelder** [comment]
With simplifying the Result model, today we settled on these variables:

Option 1:
- mdq_result (complex object that includes the non-prefixed attributes in option 2 below)

Option 2:
- mdq_status
- mdq_output (simple scalar or vector)

**Comment by leinfelder** [comment]
Refactored to use mdq_result so far.

**Comment by amoeba** [comment]
I'm not particularly passionate about either option but here are some strawmen for consideration:

### A simple check

> Given a check with the proper XPath to grab the dataset title that intends to check that the title has at least four 'words':

Option 1:

```{r}
mdq_result <- list()
mdq_result[["status"]] <- length(strsplit(title, " ")) >= 4
```

or 

```{r}
mdq_result <- list("status" = length(strsplit(title, " ")) >= 4)

Option 2:

```{r}
mdq_status <- length(strsplit(title, " ")) >= 4
```

Because we didn't wrap things up in a single, complex object, my super simple check didn't have to interact with creating a list (either beforehand or inline with setting the status).


### A slightly less simple check

> Given a check with the proper XPath to grab all of the EML otherEntity elements and their distribution URL that checks whether each of the URLs resolves to an HTTP status code of 200 and reports back any URLs for which the status was not 200:

Option 1:

```{r}
library(httr)
http_statuses <- sapply(urls, function(url) { HEAD(url)$status } )
mdq_result <- list("status" = all(http_statuses == 200))
if (any(http_statuses != 200)) {
  mdq_result[["output"]] <- as.list(paste0("The URL ", urls[which(http_statuses != 200)], " had non-200 status (was ", http_statuses[which(http_statuses != 200)], " instead.)"))
}
```

Option 2:

```{r}
library(httr)
http_statuses <- sapply(urls, function(url) { HEAD(url)$status } )
mdq_result <- list("status" = all(http_statuses == 200))
if (any(http_statuses != 200)) {
  mdq_output <- as.list(paste0("The URL ", urls[which(http_statuses != 200)], " had non-200 status (was ", http_statuses[which(http_statuses != 200)], " instead.)"))
}
```

After writing those I think I like the single object and addressing it as a list with members `status`, and `output`.

**Comment by leinfelder** [comment]
great, that's what I did in the engine :)

**Comment by leinfelder** [comment]
Now expecting "mdq_result", but will also work with a simple return value.
