### ISSUE TITLE
How can parts of a recommendation be associated, or do suites need IDs?

### ISSUE THREAD

**Issue by scgordon** [NCEAS/mdqengine#37]
Often a recommendation that an organization creates is broken up into separate, but associated parts. Sometimes users want to just test for mandatory compliance, or for identification compliance. It makes sense to write these as separate suites, but a way to associate suites is needed.

I think it might be worthwhile to make checks modular as well....

**Comment by amoeba** [comment]
Hey @scgordon, thanks for the question...

> Often a recommendation that an organization creates is broken up into separate, but associated parts.

I think I understand this use case from what I've seen out in the wild but,

> but a way to associate suites is needed

Can you please elaborate a bit? How do you mean associate? This sounds like hierarchical suites which is something we haven't talked about but I'd be happy to think more on this. In the current implementation, there are three levels of hierarchy in a suite: Suite, Check, and Check.Type. Suites contain Checks and Checks have a Type. Check results can be grouped by their Types. The current Types we use in the LTER suite are metadata, data, and congruence. Type isn't controlled right now but may need to be in the future so it might not be the right way to support your given use case.

Do the sub-suites (compliance, identification) make sense to run stand-alone? It sounds like you're saying they do make sense to run by themselves. Then would an organization's recommendation (which is made up of these sub-suites) only make sense if all the sub-suites were run?

> I think it might be worthwhile to make checks modular as well....

If I understand your meaning, checks are actually modular right now. We had always planned to allow registration of individual checks with the engine which suites can reference by their `id`. Is that what you mean by modular?

**Comment by scgordon** [comment]
I think you are right, Type isn't a solution for my issue. I don't think hierarchical is the right way to think about what I'm trying to describe. Some recommendations place more or less importance on a concept, required vs recommended, some like the LTER Completeness recommendation ascribe different documentation needs to the different recommendation profiles (parts, suites, levels.....) such as identification, access etc. My personal preference would be to give each suite an ID so that associated suites would be able to be grouped easily by a user.

It may be that a user is only interested in the concepts that are mandatory for any recommendation, so they would want to select the set of suites that included only mandatory profiles from any recommendation. I think you can only talk about the recommendation in relation to the record or collection if all the (sub) suites are run, but you could readily make sense of the record or collection containing all the concepts of the mandatory profile of the recommendation, or the mandatory and recommended.

How would the xml for an individual check look? It would work better (maybe) to define the concepts individually and then write suites with id references for the different recommendation profiles. Do you have an example of the xml that utilizes id references in a suite?

**Comment by amoeba** [comment]
PS, I put down a skeleton use case document for this in the potential-use-cases folder over here: https://github.com/NCEAS/metadig/blob/master/mdqengine/docs/use-cases/potential-use-cases/suites-can-be-associated.md so we don't lose it.

**Comment by scgordon** [comment]
I think that will work fine. Suite id is a sweet idea that I wasn't aware existed. 

In the case of recommendations with optional and required profiles, the levels would work well for identifying the different profiles. I don't think the levels will work for identifying all of the different aspects of a recommendation profile. Most recommendations that assign priorities to the profiles have at least three levels to the recommendation, with the middle layer generally being somewhere between mandatory and optional such as Recommended or Mandatory if Applicable. Other recommendations assign no priority to the profiles, or levels. We can probably work around this using suite and check ids though, it might just be the wrong area of the document to contain that kind of information.

I'd like to hear more about stores. Are they local only to the membernode or can other membernodes use them? For example, if I were the proprietor of the HDF Store, could users from ORNLDAAC or BCO-DMO test their metadata using the suites in my store, without copying them to their own store? Could they avoid forking from the ones in the HDF store and benefit from continued development? Could they just use the ids to reference the suites or are the global ids store specific?

**Comment by amoeba** [comment]
We haven't fully spec'd out the store so any of those features could be put in the table. I'm not sure where we are along those lines today in terms of implementation but I think Suites can be on any MN right now. You've touched on a few design issues that are important and not fully fleshed out just yet:

**Who runs Suites and Checks?**
Running a Suite or a single Check means doing non-sandboxed computation that will require an unknown amount of resources and time to perform. Thus it would seem very important the person responsible for the computer running the Engine accept the consequences of the Suites and Checks registered with it.

If I load a Suite into my Store, I'm assuming the responsibility for what it contains. Running Suites and Checks from remote Stores follows the same idea. But can end-users ask an Engine to run a Suite or Check that the person running the Engine doesn't trust? Maybe not.

So we could...

- Allow an Engine to run remote Suites/Checks if the owner of the Engine instance specifically allows it
- Tell the person they'll have to set up an instance of the Engine themselves if they want to run other Suites than those available to the Engine instance they're currently using

A note: Running a Suite or Check may require software that is not installed on the computer running the Engine. It's easier to assume the installer of the Engine installs the necessary dependencies for their Suites but more difficult to assume someone else running the Engine has installed dependencies implied by Suites they've never seen. Either way, we may have to tackle dependency management somehow but the remote suite use case is a little trickier to me.


**Are Suites/Checks versioned?**

With our Store concept, if we used a Member Node Store, we'd end up versioning Suites and Checks using our existing byte-level versioning system all Member Nodes use. I assume we want strongly versioned Suites and Checks.

**What happens when a Suite/Check is updated?**

Say we have an MN running the Engine and the Engine has had SuiteA registered with it. If someone obsoletes SuiteA, does the trigger the Engine to re-run the new version of SuiteA against all documents? Is this an automatic process or manual? What does the UI show the end-user (1) if their Result (the product of running a Suite on a Document) is out of date (2) if the system is running their document against the new version of the suite (do they see the old Result until the new one is generated or do they see a placeholder until then?

**Comment by leinfelder** [comment]
There is also check.type which would give a level of faceting within a suite.
